# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  namespace: practica2-201700893
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - image: jaredosuna/api_client_grpc_201700893
          name: api-server-client-grpc-201700893
          env:
            - name: SERVER_IP
              value: "localhost"
            - name: SERVER_PORT
              value: "50051"
            - name: API_PORT
              value: "3000"
          ports:
            - containerPort: 3000
        - image: jaredosuna/api_server_grpc_201700893
          name: api-server-grpc-201700893
          ports:
            - containerPort: 50051
---
# API Service on port 3000
apiVersion: v1
kind: Service
metadata:
  name: api-server-svc
  namespace: practica2-201700893
  labels:
    app: api-server
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: api-server