apiVersion: v1
kind: Pod
metadata:
  labels:
    run: api
  namespace: squidgames
  name: api
spec:
  containers:
    - image: jaredosuna/api_client_grpc_201700893
      name: client-fase2
      env:
        - name: SERVER_IP
          value: "localhost"
        - name: SERVER_PORT
          value: "50001"
        - name: API_PORT
          value: "3000"
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: squidgames
  labels:
    run: api
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    run: api