# Producer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  namespace: practica2-201700893
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - image: jaredosuna/api_server_grpc_201700893
          name: api-server-grpc-201700893
          ports:
            - containerPort: 50051
---
# Producer Service on port 50051
apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  namespace: practica2-201700893
  labels:
    app: producer
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: producer
